# Generated by Django 5.2.12 on 2026-05-02 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tickettype',
            options={'ordering': ['price']},
        ),
    ]
