# Generated by Django 5.2.12 on 2026-05-02 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_tickettype_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='tx_reference',
            field=models.CharField(blank=True, null=True, unique=True),
        ),
    ]
