# Generated by Django 5.2.12 on 2026-05-03 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_ticket_tx_reference'),
        ('payment', '0002_payment_description_payment_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='events.event'),
        ),
    ]
