# Generated by Django 5.2.12 on 2026-03-23 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authuser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(default='male', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(max_length=200),
        ),
    ]
