# Generated by Django 5.2.12 on 2026-04-06 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authuser', '0006_user_cover_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='cover_photo',
        ),
        migrations.AddField(
            model_name='user',
            name='last_active',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
