# Generated by Django 5.2.12 on 2026-05-09 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='venue',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
