# Generated by Django 5.2.12 on 2026-05-09 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIS', '0002_match_venue'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='short_hand',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
