# Generated by Django 5.2.12 on 2026-05-16 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIS', '0004_vacancy'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='organization',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='type',
            field=models.CharField(default='full time', max_length=300),
        ),
    ]
